# Generated by Django 5.1.6 on 2025-02-18 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Suissma_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meme",
            options={"verbose_name": "Meme", "verbose_name_plural": "Memes"},
        ),
    ]
