# Generated by Django 5.1.6 on 2025-02-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suissma_App', '0002_alter_meme_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ['-created_at'], 'verbose_name': 'Meme', 'verbose_name_plural': 'Memes'},
        ),
        migrations.AddField(
            model_name='meme',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
