# Generated by Django 5.1.6 on 2025-02-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suissma_App', '0003_alter_meme_options_meme_caption_alter_meme_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='local_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
