# Generated by Django 5.1.6 on 2025-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suissma_App', '0004_meme_local_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='caption',
            field=models.CharField(blank=True, help_text='Generated caption for the meme.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the meme was created.'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='image_url',
            field=models.URLField(blank=True, help_text='Public URL of the generated meme image.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='local_image_path',
            field=models.CharField(blank=True, help_text='Local file path for the stored meme image.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='prompt',
            field=models.CharField(help_text="User's input prompt for meme generation.", max_length=255),
        ),
    ]
